from api.views.member import *
from api.views.dashboard import *
from api.views.event import *
from api.views.Region import *
from api.views.Competence import *
from api.views.Domaine import *
from api.views.Specialite import *
from api.views.Langue import *
from api.views.CandidatLangue import *
from api.views.Offre import *
from api.views.Candidature import *
from api.views.Formation import *
from api.views.Experience import *
from api.views.Departement import *
from api.views.Entretien import *
from api.views.Formation import *
